from __future__ import annotations

from pathlib import Path

from .engine import render_leds
from .model import Project


def export_arduino_header(project: Project, led_points: list[tuple[float, float]], path: str | Path) -> Path:
    frame_ms = max(1, round(1000 / project.fps))
    sampled: list[tuple[int, tuple[int, ...]]] = []
    for time_ms in range(0, project.duration_ms + 1, frame_ms):
        colors = render_leds(project, led_points, time_ms)
        flat = tuple(channel for color in colors for channel in color)
        if sampled and sampled[-1][1] == flat:
            sampled[-1] = (sampled[-1][0] + frame_ms, flat)
        else:
            sampled.append((frame_ms, flat))

    lines = [
        "// Generated by CnC Light Editor. Do not edit by hand.",
        "#pragma once",
        "#include <Arduino.h>",
        "#include <avr/pgmspace.h>",
        "",
        f"constexpr uint8_t CNC_EFFECT_LED_COUNT = {len(led_points)};",
        f"constexpr uint16_t CNC_EFFECT_FRAME_COUNT = {len(sampled)};",
        "",
        "const uint16_t CNC_EFFECT_DURATIONS[] PROGMEM = {",
        "  " + ", ".join(str(duration) for duration, _ in sampled),
        "};",
        "",
        "const uint8_t CNC_EFFECT_RGB[][CNC_EFFECT_LED_COUNT * 3] PROGMEM = {",
    ]
    for _, frame in sampled:
        lines.append("  { " + ", ".join(str(value) for value in frame) + " },")
    lines.extend(["};", ""])
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination
