from __future__ import annotations

from pathlib import Path

from .engine import render_leds
from .model import Project

FIRMWARE_LED_COUNT = 68


def export_arduino_header(
    project: Project,
    led_points: list[tuple[float, float] | None],
    path: str | Path,
) -> Path:
    frame_ms = max(1, round(1000 / project.fps))
    sampled: list[tuple[int, tuple[int, ...]]] = []
    for time_ms in range(0, project.duration_ms + 1, frame_ms):
        slots = led_points[:FIRMWARE_LED_COUNT]
        slots.extend([None] * (FIRMWARE_LED_COUNT - len(slots)))
        active_colors = iter(render_leds(project, [point for point in slots if point is not None], time_ms))
        colors = [next(active_colors) if point is not None else (0, 0, 0) for point in slots]
        flat = tuple(channel for color in colors for channel in color)
        if sampled and sampled[-1][1] == flat:
            sampled[-1] = (sampled[-1][0] + frame_ms, flat)
        else:
            sampled.append((frame_ms, flat))

    lines = [
        "// Generated by CnC Light Editor. Do not edit by hand.",
        "// 59 mapped playfield LEDs + 9 zero-padded reserved LEDs = 68.",
        "// Opacity is pre-composited into the RGB channel values.",
        "#pragma once",
        "#include <Arduino.h>",
        "#include <avr/pgmspace.h>",
        "",
        f"constexpr uint8_t CNC_EFFECT_LED_COUNT = {FIRMWARE_LED_COUNT};",
        f"constexpr uint16_t CNC_EFFECT_FRAME_COUNT = {len(sampled)};",
        "",
        "const uint16_t CNC_EFFECT_DURATIONS[] PROGMEM = {",
        "  " + ", ".join(str(duration) for duration, _ in sampled),
        "};",
        "",
        "const uint8_t CNC_EFFECT_RGB[][CNC_EFFECT_LED_COUNT * 3] PROGMEM = {",
    ]
    for _, frame in sampled:
        lines.append("  { " + ", ".join(str(value) for value in frame) + " },")
    lines.extend(["};", ""])
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination
