from __future__ import annotations

import math
from pathlib import Path
import re
import unicodedata

from .engine import render_leds_with_mask
from .effect_importer import ImportedEffect
from .model import Project

FIRMWARE_LED_COUNT = 68
BYTES_PER_FRAME = FIRMWARE_LED_COUNT * 3
EFFECT_BANK_CAPACITY = 150 * 1024
TRANSPARENT_SENTINEL = (255, 0, 255)


def sample_project_frames(
    project: Project,
    led_points: list[tuple[float, float] | None],
) -> list[tuple[int, ...]]:
    """Bake the project into fixed-duration, frame-major V4 RGB data."""
    frame_ms = max(1, int(project.frame_ms or 1))
    frame_count = max(1, math.ceil(project.duration_ms / frame_ms))
    slots = list(led_points[:FIRMWARE_LED_COUNT])
    slots.extend([None] * (FIRMWARE_LED_COUNT - len(slots)))
    active_points = [point for point in slots if point is not None]

    frames: list[tuple[int, ...]] = []
    for frame_index in range(frame_count):
        time_ms = frame_index * frame_ms
        rendered, painted = render_leds_with_mask(project, active_points, time_ms)
        active_cells = iter(zip(rendered, painted))
        transparent_canvas = project.canvas_transparency_at(time_ms)
        colors = []
        for point in slots:
            if point is None:
                colors.append((0, 0, 0))
                continue
            color, is_painted = next(active_cells)
            if transparent_canvas and not is_painted:
                colors.append(TRANSPARENT_SENTINEL)
            elif project.overlay and color == TRANSPARENT_SENTINEL:
                colors.append((254, 0, 255))
            else:
                colors.append(color)
        frames.append(tuple(channel for color in colors for channel in color))
    return frames


def export_arduino_header(
    project: Project,
    led_points: list[tuple[float, float] | None],
    path: str | Path,
) -> Path:
    effect = project_to_imported_effect(project, led_points)
    return export_effect_bank([effect], path, max_bytes=None)


def project_to_imported_effect(
    project: Project,
    led_points: list[tuple[float, float] | None],
) -> ImportedEffect:
    frames = sample_project_frames(project, led_points)
    _validate_metadata(project, len(frames))
    colors = [
        [tuple(frame[index:index + 3]) for index in range(0, len(frame), 3)]
        for frame in frames
    ]
    return ImportedEffect(
        name=project.name,
        frames=colors,
        frame_ms=int(project.frame_ms or 1),
        effect_id=project.effect_id,
        symbol=f"fx_{_identifier(project.name)}",
        loops=project.loops,
        loop_frames=len(frames) if project.loop_frames == 0 else project.loop_frames,
        overlay=project.overlay,
    )


def export_effect_bank(
    effects: list[ImportedEffect],
    path: str | Path,
    max_bytes: int | None = EFFECT_BANK_CAPACITY,
) -> Path:
    _validate_effect_bank(effects, max_bytes)
    symbols = _unique_symbols(effects)
    total_bytes = sum(effect.flash_bytes for effect in effects)
    capacity_note = (
        f" of {max_bytes} bytes ({max_bytes / 1024:.1f} KiB bank)"
        if max_bytes is not None else ""
    )

    lines = [
        "#pragma once",
        "// Generated by CnC Light Editor for the V4 baked-frame firmware.",
        "// Frame-major RGB: 68 LEDs * 3 channels = 204 bytes per stored frame.",
        "// OVERLAY sentinel: (255,0,255) means transparent; painted FF00FF is exported as FE00FF.",
        f"// Effect bank: {len(effects)} effects, {total_bytes} bytes{capacity_note}.",
        "// Opacity, easing and fades are pre-composited into the RGB values.",
        "#include <Arduino.h>",
        "#include <avr/pgmspace.h>",
        "",
        "struct EffectDef {",
        "  uint8_t id;",
        "  const char* name;",
        "  const uint8_t* data;",
        "  uint16_t frames;",
        "  uint16_t frameMs;",
        "  uint8_t loops;",
        "  uint16_t loopFrames;",
        "  uint8_t overlay;",
        "};",
    ]
    for effect, symbol in zip(effects, symbols):
        mode = (
            "OVERLAY/CANVAS (FF00FF sentinel is transparent; black stays opaque)"
            if effect.overlay else "FULL (black stays black)"
        )
        lines.extend([
            "",
            f"// {effect.name}: {len(effect.frames)} frames, {effect.flash_bytes} bytes, "
            f"{effect.actual_fps:.3f} FPS; {mode}.",
            f"const uint8_t {symbol}[] PROGMEM = {{",
        ])
        for frame_index, colors in enumerate(effect.frames):
            frame = [channel for color in colors for channel in color]
            lines.append(f"  // frame {frame_index}")
            lines.append("  " + ", ".join(str(value) for value in frame) + ",")
        lines.append("};")
    lines.extend([
        "",
        "const EffectDef bakedEffects[] = {",
        "  // ID, name, data, frames, frameMs, loops, loopFrames, overlay",
    ])
    for effect, symbol in zip(effects, symbols):
        escaped_name = effect.name.replace("\\", "\\\\").replace('"', '\\"')
        loop_frames = effect.normalized_loop_frames
        lines.append(
            f'  {{ {effect.effect_id}, "{escaped_name}", {symbol}, {len(effect.frames)}, '
            f"{effect.frame_ms}, {effect.loops}, {loop_frames}, {int(bool(effect.overlay))} }},"
        )
    lines.extend([
        "};",
        "const uint8_t bakedEffectCount = sizeof(bakedEffects) / sizeof(bakedEffects[0]);",
        "",
    ])

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    temporary.replace(destination)
    return destination


def _validate_effect_bank(effects: list[ImportedEffect], max_bytes: int | None) -> None:
    if not effects:
        raise ValueError("Effect bank cannot be empty")
    seen_ids: set[int] = set()
    for effect in effects:
        if not 1 <= effect.effect_id <= 255:
            raise ValueError(f"{effect.name}: effect ID must be between 1 and 255")
        if effect.effect_id in seen_ids:
            raise ValueError(f"Duplicate effect ID {effect.effect_id}")
        seen_ids.add(effect.effect_id)
        if not effect.name.strip():
            raise ValueError("Effect name cannot be empty")
        if not effect.frames:
            raise ValueError(f"{effect.name}: frames must be at least 1")
        if not 1 <= effect.frame_ms <= 65535:
            raise ValueError(f"{effect.name}: frameMs must be between 1 and 65535")
        if not 1 <= effect.loops <= 255:
            raise ValueError(f"{effect.name}: loops must be between 1 and 255")
        if not 0 <= effect.loop_frames <= len(effect.frames):
            raise ValueError(f"{effect.name}: loopFrames must be between 0 and frames")
        for frame in effect.frames:
            if len(frame) != FIRMWARE_LED_COUNT:
                raise ValueError(f"{effect.name}: every frame must contain exactly 68 LEDs")
            if any(len(color) != 3 or any(not 0 <= channel <= 255 for channel in color) for color in frame):
                raise ValueError(f"{effect.name}: RGB values must be between 0 and 255")
    total_bytes = sum(effect.flash_bytes for effect in effects)
    if max_bytes is not None and total_bytes > max_bytes:
        raise ValueError(
            f"Effect bank uses {total_bytes} bytes, exceeding the {max_bytes} byte limit"
        )


def _unique_symbols(effects: list[ImportedEffect]) -> list[str]:
    symbols: list[str] = []
    used: set[str] = set()
    for effect in effects:
        base = f"fx_{_identifier(effect.name)}"
        symbol = base
        suffix = 2
        while symbol in used:
            symbol = f"{base}_{suffix}"
            suffix += 1
        used.add(symbol)
        symbols.append(symbol)
    return symbols


def _validate_metadata(project: Project, frames: int) -> None:
    if not 1 <= project.effect_id <= 255:
        raise ValueError("Effect ID must be between 1 and 255")
    if not project.name.strip():
        raise ValueError("Effect name cannot be empty")
    if not 1 <= int(project.frame_ms or 0) <= 65535:
        raise ValueError("frameMs must be between 1 and 65535")
    if not 1 <= project.loops <= 255:
        raise ValueError("loops must be between 1 and 255")
    if not 0 <= project.loop_frames <= frames:
        raise ValueError(f"loopFrames must be between 0 and {frames}")


def _identifier(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    identifier = re.sub(r"[^A-Za-z0-9_]+", "_", ascii_value.strip()).strip("_").lower()
    if not identifier:
        identifier = "effect"
    if identifier[0].isdigit():
        identifier = "effect_" + identifier
    return identifier
